### PR TITLE
Improvements to charging

### PR DESCRIPTION
**Pull request by gestom**
1) When charging, the PTU is turned so that the camera is facing the room. This allows to observe human activities during charging.
2) Collision prevention during the undocking process. The robot turns the PTU to check for obstacles when going backwards.
3) Head restart. The MCU 24V is switched off after successfull docking and turned on before undock. This causes the head to restart and reset its position that might be incorrectly estimated. MCU reset after undock causes the scitos_node to crash, therefore the scitos node must be respawnable.

### CODE REVIEW

**Comment by cdondrup** [comment]
I reckon we will have to test if restarting the scitos node has any negative effects for a few days before merging and releasing this.

**Comment by marc-hanheide** [comment]
yes, please, this needs testing. at least before releasing. Hence, please test it and only merge after successful test is confirmed, I presume this needs https://github.com/strands-project/scitos_drivers/pull/82 to be merged and released first?!

**Comment by marc-hanheide** [comment]
Hi guys, has this been tested? Shall it be merged?

**Comment by cdondrup** [comment]
No, hasn't been tested afaik.

**Comment by gestom** [comment]
I did a few tests only, but had to restart the scitos_node every time manually. I can make the head restarting optional, so that the node does not have to be restarted after each docking.

**Comment by Jailander** [comment]
I would do that @gestom

**Comment by gestom** [comment]
OK, done

**Comment by marc-hanheide** [comment]
does this "done" mean it's tested now and confirmed working?

**Comment by gestom** [comment]
Yes, it is tested and working. I would still recommend not to use the head restart, which is now optional through the /charging/headOff parameter that is false by default.

**Comment by lucasb-eyer** [comment]
Guys, @gestom, [seriously](https://github.com/gestom/scitos_apps/commit/34f9140b322af688ee0fe928856fc4af8e060b77#diff-697c25908dc633dc4b41566c3c8033a9R4) ? Do you want to sabotage me?

Also, might [this](https://github.com/strands-project/scitos_apps/blob/34f9140b322af688ee0fe928856fc4af8e060b77/scitos_docking/src/scitos_docking/docking.cpp#L525), [this](https://github.com/strands-project/scitos_apps/blob/34f9140b322af688ee0fe928856fc4af8e060b77/scitos_docking/src/scitos_docking/docking.cpp#L554), [this](https://github.com/strands-project/scitos_apps/blob/34f9140b322af688ee0fe928856fc4af8e060b77/scitos_docking/src/scitos_docking/docking.cpp#L584), [this](https://github.com/strands-project/scitos_apps/blob/34f9140b322af688ee0fe928856fc4af8e060b77/scitos_docking/src/scitos_docking/docking.cpp#L584), [this](https://github.com/strands-project/scitos_apps/blob/34f9140b322af688ee0fe928856fc4af8e060b77/scitos_docking/src/scitos_docking/docking.cpp#L643) and/or [this](https://github.com/strands-project/scitos_apps/blob/34f9140b322af688ee0fe928856fc4af8e060b77/scitos_docking/src/scitos_docking/docking.cpp#L669) be the offender causing strands-project/scitos_drivers#87?

**Comment by marc-hanheide** [comment]
Oh dear.... my code review was too sloppy. @gestom @Jailander What is this code suppose to do???

**Comment by marc-hanheide** [comment]
@gestom @Jailander in particular [this change](https://github.com/gestom/scitos_apps/commit/34f9140b322af688ee0fe928856fc4af8e060b77#diff-697c25908dc633dc4b41566c3c8033a9R4) is pretty terrible. We should only commit code that is working in general and not on our robot only. 
I apologise to everyone who suffered from this, @lucasb-eyer, I should check better before merging.

**Comment by lucasb-eyer** [comment]
See above PR. @gestom you might want to know about it...

**Comment by marc-hanheide** [comment]
@gestom @Jailander I'll wait until 10am for you to submit a new version ;-) Afterwards, I'll revert this pull request and re-release.

**Comment by marc-hanheide** [comment]
I'll revert it now and re-merge it when this is fixed

**Comment by lucasb-eyer** [comment]
Not that urgent for me anymore, since I worked around it locally.

~~On the other hand, why didn't you talk about it in your commit message @gestom @Jailander ? I read the full message and didn't complain because I didn't see a danger. I'm not gonna read all diffs of all strands. In case this was an accident, please **never** use `git commit -a` or `git add .` when you're not alone on the repo.~~

Edit: just saw the "Light behaviour improved" message, oh well :D

**Comment by cdondrup** [comment]
@lucasb-eyer Just a comment about the PTU movements. We are running the docking and backtrack behaviour here as well and did not observe any problems with that. I don't think that these PTU movements are the issue. They were meant to turn the PTU while charging, in case you want to observe people from the station while the robot is not doing anything, and also to look behind the robot before undocking to make sure that the space is free.

**Comment by lucasb-eyer** [comment]
OK, I just asked because I thought the limit was +-180, and this is over 300.

**Comment by cdondrup** [comment]
That's radians*100
The driver only accepts radians where as the action server works with degrees.

**Comment by lucasb-eyer** [comment]
Wow, respect for the [most subtle](https://github.com/strands-project/scitos_apps/blob/34f9140b322af688ee0fe928856fc4af8e060b77/scitos_docking/src/scitos_docking/CChargingActions.cpp#L95-L103) troll I have ever seen, we should call that unit decadians :) I'll just look away and move on I guess.

**Comment by marc-hanheide** [comment]
So... To summarise. This is not the cause of the ptu problems? The ebc parameter still needs fixing I'd say but I'm happy to put this PR back in otherwise.

**Comment by lucasb-eyer** [comment]
Oh, no this is not the PTU, it's the EBC that I was complaining about, the PTU was just a suspiction, not an assertion. Since you merged my linked PR, you can safely merge this PR here back in,

**Comment by marc-hanheide** [comment]
OK, so I devised https://github.com/strands-project/scitos_apps/pull/124 to put @gestom's changes back in place but _without_ the default EBC parameter

**Comment by marc-hanheide** [comment]
please check #124 for absence of obvious stupidity on my behalf

**Pull request merged**
