### PR TITLE
[scitos_door_pass] DoorCheck action has been moved from strands_navigation_msgs

### PR DESCRIPTION
**Pull request by cdondrup**
To reduce dependencies for release. The files had only one commit in its history, therefore it has just been moved instead of using git subtree and creating a lot more unnecessary commits.

### CODE REVIEW

**Comment by cdondrup** [comment]
Needs https://github.com/strands-project/strands_msgs/pull/27 and https://github.com/strands-project/strands_utils/pull/117 merged.

**Comment by cdondrup** [comment]
Not sure why the build still fails.
It says that it cannot find `strands_navigation_msgs` but none of the package has that as a dependency any more. @marc-hanheide do you have an idea?

Builds fine when building the whole system on my machine though. Should therefore be fine to merge.

**Comment by cdondrup** [comment]
I know this a bit off topic but could it be possible that the Jenkins script does not build the fork from which the PR is initiated but just the main repo? This bit of output got me a bit suspicious:

```
Creating rosinstall file for repo list
Using devel distro file to download repositories
rosinstall file for all repositories: 
 - git: {local-name: scitos_apps, uri: 'https://github.com/strands-project/scitos_apps.git',
    version: hydro-devel}

Install repo list from source
Executing command 'rosinstall /tmp/test_repositories/src_repository /var/lib/jenkins/jobs/pr-hydro-scitos_apps/workspace/ARCH_PARAM/amd64/UBUNTU_PARAM/precise/label/devel/repo.rosinstall --catkin'
rosinstall operating on /tmp/test_repositories/src_repository from specifications in rosinstall files  /var/lib/jenkins/jobs/pr-hydro-scitos_apps/workspace/ARCH_PARAM/amd64/UBUNTU_PARAM/precise/label/devel/repo.rosinstall
(Over-)Writing /tmp/test_repositories/src_repository/.rosinstall
Cloning into '/tmp/test_repositories/src_repository/scitos_apps'...
[scitos_apps] Fetching https://github.com/strands-project/scitos_apps.git (version hydro-devel) to /tmp/test_repositories/src_repository/scitos_apps
[scitos_apps] Done.

rosinstall update complete.
Notification recipients: cburbridge@gmail.com cdondrup@lincoln.ac.uk cdondrup@todo.todo tkrajnik@lincoln.ac.uk
Get build dependencies of repo list
Get the dependencies of source folder /tmp/test_repositories/src_repository
In folder /tmp/test_repositories/src_repository, found packages: scitos_cmd_vel_mux, scitos_dashboard, scitos_docking, scitos_door_pass, scitos_ptu, scitos_ramp_climb, scitos_teleop, scitos_touch
Install build dependencies of repo list: roscpp, rospy, scitos_msgs, std_msgs, libqt4-dev, rqt_gui, rqt_gui_cpp, catkin, yocs_cmd_vel_mux, diagnostic_msgs, roslib, rqt_robot_dashboard, message_generation, actionlib, actionlib_msgs, message_runtime, image_transport, sensor_msgs, geometry_msgs, joy, libgsl, libblas-dev, mongodb_store, strands_navigation_msgs, nav_msgs
```

It looks like it is just downloading the strands-project hydro-devel version and tries to build it.

**Comment by marc-hanheide** [comment]
Everything is will possible. Though I would have hoped to spot that
earlier. I'll check  tomorrow.

Cheers

Marc

**Comment by cdondrup** [comment]
This will be merged in order to proceed with the release efforts.

**Comment by marc-hanheide** [comment]
yeah... jenkins has a problem, I'm working on it

**Comment by marc-hanheide** [comment]
So, jenkins problem is now fixed and pull requests are tested properly. Also, I added two missing deps in scitos_apps and now it seems to build just fine.

**Pull request merged**
