### PR TITLE
Clamped pan and tilt values to limits

### PR DESCRIPTION
**Pull request by RaresAmbrus**
Committed with @nilsbore's username, who's signed in on the robot :angry:

### CODE REVIEW

**Comment by cdondrup** [comment]
Builds fine... I will try it here after the merge.

**Comment by RaresAmbrus** [comment]
Thanks @cdondrup, should fix the PTU problems. I was checking and clamping the start & end pan & tilt angles, and not the intermediate ones. And those were not the values I gave you @hawesie :smile:

**Comment by cdondrup** [comment]
@RaresAmbrus works fine now. Thanks for the fix!

**Comment by RaresAmbrus** [comment]
Great! Sorry the bug was there to begin with ...

**Pull request merged**
