### PR TITLE
Joystick name

### PR DESCRIPTION
**Pull request by cburbridge**
This changes the joystick to /dev/input/rumblepad. The reason for the change is that after installing Ubuntu 12.04 64bit, the joysitck became /dev/input/js0 not /dev/input/js1. So I have created a udev rule to make it always /dev/input/rumblepad.

To use, copy the udev file to /etc/udev/rules.d/, remove and replug joystick dongle.

### CODE REVIEW

**Comment by marc-hanheide** [comment]
I'm slightly reluctant... not everybody will have that udev rule in place and things like this always add a lot of confusion, such as "why don't I see a js1 on my robot when I plug it in? something is utterly wrong, I better reboot". I'd rather enforce people to give an argument to the launch file that is required. The udev rule it self is very useful, for people who know what they are doing and actually have root access. For everyone remote controlling the robot on a desktop installation for instance, it's more confusing than helpful, I fear.

**Comment by cburbridge** [comment]
I had not considered using it on a desktop.... I have added an optional parameter.
if launched as

```
roslaunch scitos_teleop scitos_teleop
```

then the default "/dev/js1" is used.

if launched as

```
roslaunch scitos_teleop scitos_teleop js:=/dev/js0
```

then the "/dev/js0" is used.

if launched as

```
JOYSTICK_DEVICE=/dev/joydev roslaunch scitos_teleop scitos_teleop
```

then the default "/dev/joydev" is used.

This way on our robot I have the environment variable set

```
export JOYSTICK_DEVICE=/dev/input/rumblepad
```

and don't have to supply the parameter. However, if I do supply the parameter then it always takes over the default and the env variable.

So now the udev is just an optional robot configuration thing that I might move over to scitos_robot at some point

**Comment by marc-hanheide** [comment]
That sounds like a perfect solution to me. And apologies for the typos in my previous comment... one shouldn't reply on the phone.

**Comment by marc-hanheide** [comment]
also, can you check that the udev rule is actually correct. To me it seems there has been a copy and paste error (missing closing double quotes in NAME)...

**Comment by cburbridge** [comment]
oops.

**Comment by cburbridge** [comment]
So can I merge this?

**Comment by marc-hanheide** [comment]
Yeah, feel free.

Marc

**Pull request merged**
