### PR TITLE
nasty hotfix get rid of seg fault: removed debugging output 

### PR DESCRIPTION
**Pull request by marc-hanheide**
This was necessary because docking continued to crash to werner. I see my local workspace was not updated before I did this fix, so this cannot be merged. So, this is more for documentation than actually ever to be really merged. @cdondrup @Jailander I'm not sure what state you left werner in, I thought you tested docking, but it was neither running nor would it restart. I recompiled it, and still wouldn't start. Hence, I removed the problematic image_transport calls and now it works at least. Awaiting suggestions from your end.

### CODE REVIEW

**Comment by marc-hanheide** [comment]
OK, merged this with the main upstream branch, in case we want to merge it...

**Comment by cdondrup** [comment]
We tested this on Linda but couldn't on Werner because no one there in case it would have left him stranded. So no real testing happened. Since the other approach didn't work either we just went for it.

**Comment by marc-hanheide** [comment]
but it didn't even start...

**Comment by cdondrup** [comment]
But we ran it. I'm sure it started... Weird.sorry about that.

**Comment by marc-hanheide** [comment]
odd... well, it's kind of working for now, But also Peter has image_transport related issues. so I opened https://github.com/ros-perception/image_common/issues/34 to see what they say.

**Comment by marc-hanheide** [comment]
Now that everything has been rebuilt, can we update Linda and see if everything works again?

**Comment by cdondrup** [comment]
On it

**Comment by cdondrup** [comment]
Everything works fine on Linda. The hotfix does not seem to be necessary any more.

**Pull request closed without merging**
