### PR TITLE
PTU sweep action server

### PR DESCRIPTION
**Pull request by RaresAmbrus**
Added feedback and well defined action message.

### CODE REVIEW

**Comment by marc-hanheide** [comment]
stupid question: who is user "default"?

**Comment by RaresAmbrus** [comment]
For some reason, whenever I commit to my branch from the robot, even though I authenticate myself with my user and password, git records the user as default. No clue why but I haven't really looked into it till now.

**Comment by cdondrup** [comment]
Git does not care about the username and password you logged in with. It will always assume that the user is the one specified by `git config --local/--global user.name and user.email`.

**Comment by RaresAmbrus** [comment]
I'm merging this as it's needed for the long term patroller with logging. I'll add any other changes and merge them later.

**Comment by cdondrup** [comment]
I would still like it better if you would have used the ptu_action_server to move the ptu instead of publishing to /ptu/cmd. But I don't know about the others.

**Comment by RaresAmbrus** [comment]
At first glance that doesn't seem like an efficient implementation, because of the send goal & wait for the result from the other action server. If you're sure that works well I don't mind changing the current implementation.

**Comment by cdondrup** [comment]
Yes, this works very well. And as @marc-hanheide and @hawesie already pointed out, duplication of code should be avoided if possible because the other ptu_action_server is already well written and ensures thread safety and does not have hard coded timeouts in it.
My two cents: I also think that the `print` statements should either be log messages or removed and that calling it `ptu_actionserver` compared to the `ptu_action_server` is a bit misleading because it is more of a `ptu_sweep_action_server` I think.

**Comment by RaresAmbrus** [comment]
Thanks for the feedback @cdondrup. I have re-implemented some functionality due to efficiency concerns, but I am aware that we should reuse existing components as much as possible.
I will test out the method that you suggest, and if it's feasible I will integrate it.

**Pull request merged**
