### PR TITLE
Docking now can use laser for the final approach

### PR DESCRIPTION
**Pull request by gestom**
This could improve docking in cases that camera topics are getting slow. Requires testing at TSC site.

### CODE REVIEW

**Comment by hawesie** [comment]
This has conflicts which need resolving.

I will test on Monday at TSC. Do I need to recalibrate?

**Comment by gestom** [comment]
No, recalibration is not required. I will join you on Monday for the testing. IMHO, the laser detection can be improved and it should be possible to dock it faster and with a higher precision.

**Comment by marc-hanheide** [comment]
Will this be resolved and/or used?

**Comment by hawesie** [comment]
We definitely used it. I'm not sure of the status on Betty now. Maybe @bfalacerda or @heuristicus can comment.

**Comment by bfalacerda** [comment]
betty isn't using this atm, I removed it when I started testing docking in bham to get it to a state where I knew it worked before.

**Comment by marc-hanheide** [comment]
Hi, I presume this is some work by @gestom (even though it shows as @cdondrup, please unset the `user.email` and `user.config` globally Linda...) I obviously would have preferred if the new feature would be presented in a new PR. Everything from add9a6448717ddb745e2061cd567cbd0f76b87d0 onwards should be removed from the PR and instead be presented in a separate one which is (if possible) based on the main branch and not this one. Please, in the future @gestom just branch off before implementing new features. Just do `git checkout -b toms_cool_new_feature_2342` or similar before starting to work. Thanks.

**Comment by marc-hanheide** [comment]
Or @Jailander were you involved in this, too? Can you help @gestom to sort it out?

**Comment by Jailander** [comment]
I wasn't I am not sure this was @gestom 's intention I will ask him whe he recovers and sort it out

**Pull request closed without merging**
