### PR TITLE
Removed scitos_apps_msgs packages

### PR DESCRIPTION
**Pull request by cdondrup**
The messages, services, and actions are now in the respective packages instead of the message dump package.

### CODE REVIEW

**Comment by cdondrup** [comment]
This pull request required a bit of refactoring. The above pull requests have to be merged together with this PR.

This change is meant to prepare the repository for release (see #94) and helps to keep the structure neat and tidy.

**Comment by marc-hanheide** [comment]
What's the procedure for these kinds of more involved refactoring? I suppose, as scitos_apps is one of the "earlier" repositories in the dependency graph we should be fairly generous in accepting changes further down the line. Alternatively, we could actually create new branches that we then accept this pull requests in. But I'd rather go for "tabula rasa" and simply accept the pull requests and then get those other repositories to be configured for jenkins ASAP as well to get a better understanding of where we are. 
So, my suggestion, @cdondrup merges all those pull requests.

**Comment by marc-hanheide** [comment]
Building the pull request obviously failed because `scitos_door_pass` still has `strands_nvaigation_msgs` as a dependency. I think this should be move into this repository, shouldn't it?

**Comment by hawesie** [comment]
Which one should be moved? Your "this" is a bit ambiguous.

**Comment by marc-hanheide** [comment]
"This" was to mean "scitos_apps"... but more precisely, I think it's the door_pass action msgs that should be moved, not the whole of `strands_navigation_msgs` I suppose. I don't see why that action would be in another repo or do I miss a point?

**Comment by cdondrup** [comment]
I agree. Can move the https://github.com/strands-project/strands_msgs/blob/hydro-devel/strands_navigation_msgs/action/DoorCheck.action once this PR is merged.

**Comment by hawesie** [comment]
I think there was a general misunderstanding about having messages independent of nodes that use them. Whilst it allows more future flexibility, it does create complex software dependencies which we should avoid, so I'm happy for all messages to be moved to their principle repos as required.

**Comment by cdondrup** [comment]
So I'll merge all of these PRs then.

**Pull request merged**
