### PR TITLE
updating metric map ptu server to use moved flir_d46 ptu server

### PR DESCRIPTION
**Pull request by cburbridge**

### CODE REVIEW

**Comment by RaresAmbrus** [comment]
@cburbridge Should I merge this ? We would have to replace the scitos_drivers ptu action server with the sctios_ptu one. Or maybe as you said, leave it till after G4S.

**Comment by cburbridge** [comment]
I don't remember making this pull request, thought I had only thought about it :-) Will this effect anything going on in the care scenario? If it is only going to effect the G4S run, then merging should be fine.

**Comment by cdondrup** [comment]
Last thing I know is there is no metric mapping at AAF. But better ask @todmaro and @arbeitor as well.

**Comment by RaresAmbrus** [comment]
I'm pretty sure the metric maps aren't used at AAF, but my concern was related to the fact that the scitos_ptu action server isn't launched right now, we are still using the old one from scitos_drivers.

**Comment by cdondrup** [comment]
For the idle behaviour I created I'm also using the one from drivers. So I is @arbeitor to look at the fire extinguisher I guess. Charging is using the driver directly without the server. Nothing else is moving the ptu at AAF AFAIK.

**Comment by cdondrup** [comment]
Now G4S and AAF are over. @cburbridge Is this PR still relevant? If so, please fix the conflicts. If not, please close.

**Comment by cdondrup** [comment]
Since my last ping on this PR was over a month ago, I guess these changes are not relevant to anyone. If no one objects, e.g. @cburbridge @RaresAmbrus, I will close this PR by the end of business today.
If this still contains relevant changes please let me know and fix the conflicts which prevent the merging.

**Comment by cdondrup** [comment]
Well then, please reopen with updated version if still necessary.

**Pull request closed without merging**
