### PR TITLE
Fixes for door passing behaviour

### PR DESCRIPTION
**Pull request by hawesie**
Two changes:

1) counts misdetections which were previously ignoring, causing it to never fail when not facing a door.

2) changed passCounter reset to -30 instead of -50 which stops the robot a little earlier when moving successful. this prevents Bob for charging off down a corridor when leaving an office.

Also added a little more logging for me to understand things and switched to ros rate objects for clarity.

### CODE REVIEW

**Comment by hawesie** [comment]
@cdondrup @arbeitor @ToMadoRe you may want to try this for AAF, or not.

**Comment by hawesie** [comment]
@BFALacerda I've now added a check to see if the robot is moving away from the target pose. Please can you test this on Bob today or tomorrow? You don't need to merge this PR, just update `scitos_apps` on Bob as he's set to use this branch anyway. For the waypoints, just make sure they're in enough space for the robot to escape using move_base if necessary (as you rightly pointed, the door could be closed). Also the two waypoints on either side of the door should be roughly pointing at each other as the robot turns to face the target pose (i.e. the next way point) before traversing. Thus the placement of both waypoints can influence. If you could also test with closed doors and partially open ones, that would be great (as the new changes would certainly come in to play when the door is closed).

**Comment by cdondrup** [comment]
Has this been tested and used at G4S? Can it be merged @cburbridge @BFALacerda ?

**Comment by cdondrup** [comment]
Before the release preparation I want to get rid of all current PRs for this repository. 
Has this version of the door pass been tested at G4S, @hawesie @BFALacerda @cburbridge? If so I will merge it since it also contains changes to docking which are necessary to work with the new datacentre.

**Comment by bfalacerda** [comment]
we ended up not using this version because the detection part was not working in g4s. We're using a simplified version that just tries to go through the space in front of the robot without detecting anything. The simplified version was re-written in python because the c++ version would stop working once in a while and needed to be restarted. I re-wrote it in python because I wasn't being able to edit the c++ code (not my cup of tea).

The version we ended up using in g4s is already merged. It needs some code cleaning though, it's full of wrongly formatted prints:

https://github.com/strands-project/scitos_apps/blob/hydro-devel/scitos_door_pass/scripts/door_pass.py

**Comment by cdondrup** [comment]
Ok, so this means this PR does not have to/shouldn't be merged? If it is not merged we will need the changes @hawesie made to the docking (0ba3eb2f0de8463e3855c31c764b4bf525f67519) in a separate PR.

**Comment by bfalacerda** [comment]
Yes, I wouldn't merge it as it ended up not being used in the deployment

**Comment by cdondrup** [comment]
Ok, I will recreate the changes for mongodb_store in another PR and close this one. Thanks @BFALacerda

**Pull request closed without merging**
