### PR TITLE
Adding scitos_ptu action server

### PR DESCRIPTION
**Pull request by RaresAmbrus**

### CODE REVIEW

**Comment by cdondrup** [comment]
Two questions:
- I thought you wanted to do a PTU sweep when entering a room. This commit now looks like it does the same as: https://github.com/strands-project/scitos_drivers/blob/master/flir_pantilt_d46/src/ptu_action_server.py So you would still have to do the sweep yourself, right?
- I don't really like the vector of magic numbers in the goal. Why not use single easily understandable variables for pan_max, min, step, and the tilt equivalent? Also the hard limit of 3 Seconds to decide if the PTU failed to move to the location should be set in the goal and not hard coded imo.

**Comment by RaresAmbrus** [comment]
@cdondrup 
Actually the two scripts do slightly different things - the one you pointed to has to be called repeatedly with different pan & tilt angles, the one I added takes a start, stop and increment angles and does the sweep. And these parameters are added in the list of waypoints, and passed to the ptu action server whenever such a waypoint is reached. 
Regarding your second point, I kept the same format as we currently use to pass goal information in the smash state machine. (first 7 parameters are fed into move base, the rest, if they exist are fed into the ptu action server). If I understand you correctly, you were saying I should add a special message for the data I'm passing to the ptu action server right ? That would definitely increase readability, I'll look into it tomorrow.

**Comment by cdondrup** [comment]
Ah, ok. But in that case you could have saved yourself a lot of hassle if you would have used the ptu action server form the scitos_driver package to actually move it. You wouldn't have to take care of checking whether it arrived at the position or not and so on. But at the moment there is a great overlap between your code and the other ptu_action_server.
Yes you are right. Using such a vector might be handy if you know what your doing but creating readable variables would enable more people to use it much faster. But you can just use the .action file to create those. No need for another message. Just something like 

```
#goal
int32 pan_max
int32 pan_min
int32 pan_step
(same for tilt)
int32 timeout
---
#result
---
#feedback
sensor_msgs/JointState ptu_pose
```

would be nice imo. Or if you want to keep using the JointState message (which imo isn't a good choice for this purpose) you should make sure that you use the `name` field to check which position is which and not, e.g. just assume that 0 always is the panstart.

Just another remark: If I am not mistaken, the convention is to put the `action` directory into the root directory of the package and not into `src`.

**Comment by marc-hanheide** [comment]
Hi, 

if I may add my two cents to this: I agree with @cdondrup that replication of functionality should be avoided, in particular as the ptu action server in scitos_driver is well-written already. Just to implement the actual sweeping here an using the ptu action server makes _much_ more sense and makes everything more readable, too.

For the second thought about the parameters, I'd also agree that the semantics are flawed. If it is named JointState, it should be a JointState, otherwise another type should be used.

Another thing:
I think the action should send feedback whenever it reached a position, so that other components could react upon this (e.g. take a snapshot in that moment). Right now it seems no feedback is given,right?

**Comment by hawesie** [comment]
Agreed with @marc-hanheide. We should reuse existing component functionality and build in a way that supports this.

**Comment by RaresAmbrus** [comment]
I implemented this action server because I wanted a complete sweep, defined by a few parameters (start pan, stop pan, etc.). Currently this is integrated in the state machine, where I've added a pan tilt state from where I call this action server which executes a complete sweep. 

What everybody in this thread seems to be suggesting is repeatedly calling the script from the scitos_driver package. That means that from the smach state I would initiate a pan and tilt action using the scitos_driver script, wait for it to finish, initiate a new one, and so on for the whole range of the sweep operation. I wanted to avoid this repeated calling of the action server and waiting for its feedback, and hence I replaced it with a single script which executes the sweep more or less continuously. Does it really make sense to repeatedly call the action server from the scitos_driver package? 

As I said earlier, I agree about the parameters and I'm looking into that.

As a note, this was added because I wanted to pan and tilt the xtion after reaching some waypoints during a patrol run (for example in the offices and not in the corridor). In the state machine, logging is automatically started at the beginning of the sweep and stopped at the end. Currently feedback is sent once the action has been completed; I didn't see the need to add intermediate feedback, since the action is defined as the complete sweep. Moreover, defining specific pan&tilt positions for different waypoints is not very easy to do, hence why I went with a complete sweep operation.

**Comment by cdondrup** [comment]
You don't have to call it in the state machine but can just write a ptu sweep action server which encapsulates that calling using just two simple nested loops. This is what we did before we noticed that you are working on the same stuff. It is not very elaborate but it does the sweep and is easy to call: https://github.com/Jailander/scitos_3d_mapping/blob/master/scitos_PTU_sweep/scripts/PTU_sweep.py

**Comment by RaresAmbrus** [comment]
Ok, I understand that you are reusing the action server from the scitos_driver package by calling it repeatedly from your own action server. I bypassed the scitos_driver action server and am sending commands directly to the ptu. My question was whether your approach does not add complexity and delays (lines 43-45 sending a goal and waiting for feedback from the server)? If this is the way to go then you should merge this and I will update the long term patroller to use your script.

**Comment by Jailander** [comment]
Hi,

That script was just preliminary work as @cdondrup told you, however, the idea of adding the feedback was to make sure at least one point cloud is captured at some specific positions, this is not a big issue since registration should be able to deal with point clouds taken at any point, so you can go either way.

P.S: You should also consider that having feedback is important for error detection and self diagnosis.

**Comment by RaresAmbrus** [comment]
I guess we haven't really talked about how logging at different waypoints will work, and hence why there seems to be a difference of opinions. Right now we start logging as soon as we start sweeping and we stop logging once the sweeping is done. We log all the camera images throughout the sweep, and we don't wait for the ptu to reach a position before recording a snapshot; we record the position of the camera when the snapshots are taken, as it is a part of the TF. 

Right now I was using the robot TF and the other topics where the ptu state is published as feedback for error detection and diagnosis, but I can add it in the action server as well.

**Pull request closed without merging**
