### PR TITLE
Pushed my master branch by mistake. Reverting.

### PR DESCRIPTION
**Pull request by RaresAmbrus**
Revert "Merge remote-tracking branch 'upstream/master'"

This reverts commit 80f8d7d992efb00a04a9378009a5b7fd49d8540d, reversing
changes made to 1b8a31432e82d18a1ae3c38a672fb06a82185247.

### CODE REVIEW

**Comment by cdondrup** [comment]
@RaresAmbrus I think this removes a lot more than just your changes now. The whole rampclimb would be removed for example. Is this intended?

**Comment by RaresAmbrus** [comment]
This is a PR for the master branch, and I'm not sure the ramp climb had been merged in there to begin with. Anyway I think I can cancel this merge since we're not really using the master branch.

**Comment by cdondrup** [comment]
Yes, the master branch is deprecated anyway.

**Comment by RaresAmbrus** [comment]
Thanks @cdondrup.

**Pull request closed without merging**
