### PR TITLE
Change PTU max velocity.

### PR DESCRIPTION
**Pull request by cburbridge**
This reduces the maximum velocity the PTU is controlled with in ptu_follow_frame. The previous value of 3 rad/s causes the PTU to loose calibration when the frame to follow was far from centred.

### CODE REVIEW

**Comment by cburbridge** [comment]
As far as I know this change only effects the object learning since nothing else has used my ptu_follow_frame package. @marc-hanheide please merge and release...

**Comment by marc-hanheide** [comment]
sir, yes, sir!

**Comment by marc-hanheide** [comment]
released now, after a long-winded process discussed in  https://github.com/strands-project/scitos_apps/commit/df7aea03f367933eb8171b8930cabce60349bc0a#commitcomment-14897218 and https://github.com/strands-project/strands_systems/pull/114#issuecomment-163432083

**Comment by cburbridge** [comment]
thanks!

**Pull request merged**
