### PR TITLE
Merged autonomous_patrolling repo into scitos_apps

### PR DESCRIPTION
**Pull request by cdondrup**
The former empty scitos_apps repository now contains the content of the autonomous_patrolling repository because these are basically apps which can run on the robot and the simulator and do not involve navigation or any of the other packages.
I additionally created a scitos_teleop package inside the scitos_apps package which contains the launch files for all the apps involving teleoperation.

Still to come is the documentation on the wiki page and a catkinization of the patroller package.

### CODE REVIEW

**Comment by hawesie** [comment]
I'm not sure that autonomous patrolling should be put in this repo. I think it's more of a larger, more complex collection of behaviours that are not robot (i.e scitos) specific, and there deserves its own repository (as it already has). The teleoperation nodes should go in here though, as they're relatively stand-alone and robot-specific. Compare to [http://ros.org/wiki/pr2_apps](http://ros.org/wiki/pr2_apps).

**Comment by bfalacerda** [comment]
Maybe the patroller package should go to a new autonomous_navigation repo?

**Comment by cdondrup** [comment]
I agree that the patroller might be better of in an autonomous navigation repository but as @hawesie said, the joystick remote control should go into the apps repository (according to the pr2 structure). Since the map and waypoint recording is also done via teleoperation (using certain buttons on the joypad to save maps and waypoints), I figured that it might be best if bundled together in one teleop package. But on the other hand it also uses higher level mapping opperations which might not be suitable for the apps repository. So if the predominant opinion is that it should go into the autonomous navigation repository too then I am happy to change the structure and move the teleop here and everything else into an autonomous navigation repo.

**Comment by bfalacerda** [comment]
I was thinking of keeping all the joypad related stuff in the apps repo, 
and just the patroller in the autonomous navigation repo. For now we 
only have a waypoint patroller that requires a map and a waypoints file 
but eventually we'll have other autonomous navigation related code. The 
joypad based map_saver and waypoint_recorder are needed to create the 
files for the patroller but they are not really autonomous nagivation 
related.

**Comment by cdondrup** [comment]
That's what I thought too but they are not really app related in sense of the pr2_apps repo either.... So it might actually be better to keep them as apps in the autonomous repo stuff but not in the actual scitos_apps repo?!

**Comment by hawesie** [comment]
I think we should separate the map saving stuff into a separate node from the more generic robot movement stuff (if it isn't already), then the map saving teleop can stay in autonomous patrolling repo, and the robot driving teleop can go in scitos_apps.

**Comment by cdondrup** [comment]
You are right. I will open a new issue for this and start working on it tomorrow. I will also close this pull request and will just move the rumbelpad_control into this package.

**Pull request closed without merging**
